# fly.toml app configuration file generated for gino on 2025-08-24T15:47:33+09:00
#

# fly.toml

app = 'gino'
primary_region = 'nrt'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false   # 비활성화하여 항상 켜진 상태로 유지
  auto_start_machines = true
  min_machines_running = 1    # 최소 1대의 머신을 항상 실행
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
